# This Notebook allows you to view the results of all the classes implemented in the context of the class.

# Class 1

## Exercise 1 -> Made on the exercise_1.ipynb on this folder

PATH: /si/exercices_evaluation/exercise_1.ipynb

## Exercice 2.1 -> Dropna Implementation Test

In [22]:
from si.data.dataset import Dataset
from si.io.csv_file import read_csv

df_na = read_csv('../datasets/iris/iris_missing_data.csv', sep=',', features=True, label=True)

print('Random sample  before dropna:')
print(df_na.X[1:4])
df_na.dropna()
print('Random sample  after dropna:')
print(df_na.X[1:3])

Random sample  before dropna:
[[4.9 3.  1.4 0.2]
 [4.7 nan 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
Random sample  after dropna:
[[4.9 3.  1.4 0.2]
 [4.6 3.1 1.5 0.2]]


## Exercise 2.2 -> Fillna Implementation Test

In [23]:
from si.data.dataset import Dataset
from si.io.csv_file import read_csv

df_na = read_csv('../datasets/iris/iris_missing_data.csv', sep=',', features=True, label=True)

print('Random sample before fillna:')
print(df_na.X[2])
df_na.fillna(0)
print('Random sample after fillna:')
print(df_na.X[2])

Random sample before fillna:
[4.7 nan 1.3 0.2]
Random sample after fillna:
[4.7 0.  1.3 0.2]


## Exercise 2.3 -> Remove_by_index Implementation Test

In [24]:
df_na = read_csv('../datasets/iris/iris_missing_data.csv', sep=',', features=True, label=True)

print('Random sample before remove_by_index:')
print(df_na.X[1:4])
df_na.remove_by_index(2)
print('Random sample after remove_by_index:')
print(df_na.X[1:3])

Random sample before remove_by_index:
[[4.9 3.  1.4 0.2]
 [4.7 nan 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
Random sample after remove_by_index:
[[4.9 3.  1.4 0.2]
 [4.6 3.1 1.5 0.2]]


## Optional Evaluation
More examples of how to use these methods
to the script/notebook of Exercise 1 

PATH: /si/scripts/dataset.ipynb

# Class 2

## Exercise 3.1/3.3 -> SelectPercentile Implementation Test

In [25]:
from si.io.csv_file import read_csv
from si.feature_selection.select_percentile import Selectpercentile
from si.statistics.f_classification import f_classification

file = "/home/sa_bruno/Documentos/GitHub/si/datasets/iris/iris.csv"
dataset = read_csv(file, features= True, label=True)
print (f"Total = {len(dataset.features)}")

perc_0 = 0
perc_0_25 = 0.25
perc_0_50 = 0.50
perc_0_75 = 0.75
perc_1 = 1.0

select_percentile = Selectpercentile(f_classification, perc_0)
filtered_dataset =  select_percentile.fit_transform(dataset)
print(f"Percentile = {perc_0} , Selected Features = {len(filtered_dataset.features)}")


select_percentile = Selectpercentile(f_classification, perc_0_25)
filtered_dataset =  select_percentile.fit_transform(dataset)
print(f"Percentile = {perc_0_25} , Selected Features = {len(filtered_dataset.features)}")

select_percentile = Selectpercentile(f_classification, perc_0_50)
filtered_dataset =  select_percentile.fit_transform(dataset)
print(f"Percentile = {perc_0_50} , Selected Features = {len(filtered_dataset.features)}")

select_percentile = Selectpercentile(f_classification,perc_0_75)
filtered_dataset =  select_percentile.fit_transform(dataset)
print(f"Percentile = {perc_0_75} , Selected Features = {len(filtered_dataset.features)}")

select_percentile = Selectpercentile(f_classification, perc_1)
filtered_dataset =  select_percentile.fit_transform(dataset)
print(f"Percentile = {perc_1} , Selected Features = {len(filtered_dataset.features)}")

Total = 4
Percentile = 0 , Selected Features = 4
Percentile = 0.25 , Selected Features = 1
Percentile = 0.5 , Selected Features = 2
Percentile = 0.75 , Selected Features = 3
Percentile = 1.0 , Selected Features = 4


## Additional examples on:

PATH: /si/scripts/feature_selection.ipynb

# Class 3
## Exercise 4 -> Implementation of the Manhattan distance Test

In [26]:
import numpy as np
from sklearn.metrics.pairwise import manhattan_distances as manhattan_distances_skl
from si.statistics.manhattan_distance import manhattan_distance

x = np.array([1, 2, 3])
y = np.array([[1, 2, 3], [4, 5, 6]])
our_distance = manhattan_distance(x, y)
    
# using sklearn    
sklearn_distance = manhattan_distances_skl(x.reshape(1, -1), y)
assert np.allclose(our_distance, sklearn_distance)

print(f"our distance = {our_distance}")
print(f"sklearn distance = {sklearn_distance}")

our distance = [0 9]
sklearn distance = [[0. 9.]]


# Exercise 5.1 -> Implementation of the PCA Class Test

In [27]:
from si.data.dataset import Dataset
from si.decomposition.pca import PCA


dataset = Dataset(X=np.array([[0, 2, 0, 3],
                            [0, 1, 4, 3],
                            [0, 1, 1, 3]]),
                y=np.array([0, 1, 0]),
                features=["f1", "f2", "f3", "f4"],
                label="y")
        
pca = PCA(n_components=3)
pca.fit_transform(dataset.X)

print(f"Explained variance: {pca.explained_variance}")
print()
print(f"Components: {pca.components}")
print()
print(f"Mean: {pca.mean}")
print()
print(f"Original data: {dataset.X}")
print()
print(f"Transformed data: {pca.fit_transform(dataset.X)}")


Explained variance: [4.50000000e+00 1.66666667e-01 1.33372984e-33]

Components: [[ 1.11022302e-16  1.96116135e-01 -9.80580676e-01  0.00000000e+00]
 [ 5.55111512e-17 -9.80580676e-01 -1.96116135e-01  0.00000000e+00]
 [-1.00000000e+00 -1.11022302e-16  0.00000000e+00  0.00000000e+00]]

Mean: [0.         1.33333333 1.66666667 3.        ]

Original data: [[0 2 0 3]
 [0 1 4 3]
 [0 1 1 3]]

Transformed data: [[ 1.76504522e+00 -3.26860225e-01 -7.40148683e-17]
 [-2.35339362e+00 -1.30744090e-01  3.70074342e-17]
 [ 5.88348405e-01  4.57604315e-01  3.70074342e-17]]


## Exercise 5.2 -> Test of the PCA Class using iris.csv

In [28]:
# using Iris dataset

from sklearn.decomposition import PCA as PCA_skl
from si.decomposition.pca import PCA

data = read_csv('/home/sa_bruno/Documentos/GitHub/si/datasets/iris/iris.csv', sep=',', features=True, label=True)

pca = PCA(n_components=3)
pca.fit_transform(data.X)

pca_skl = PCA_skl(n_components=3)
pca_skl.fit_transform(data.X)

print('Explained Variance')
print('Our')
print(pca.explained_variance)
print()
print('Sklearn')
print(pca_skl.explained_variance_)
print()
print()

print('Components')
print('Our')
print(pca.components)
print()
print('Sklearn')
print(pca_skl.components_)
print()
print()

print('Mean')
print('Our')
print(pca.mean)
print()
print('Sklearn')
print(pca_skl.mean_)    
print()
print()

Explained Variance
Our
[4.22484077 0.24224357 0.07852391]

Sklearn
[4.22484077 0.24224357 0.07852391]


Components
Our
[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]
 [ 0.58099728 -0.59641809 -0.07252408 -0.54906091]]

Sklearn
[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]
 [-0.58099728  0.59641809  0.07252408  0.54906091]]


Mean
Our
[5.84333333 3.054      3.75866667 1.19866667]

Sklearn
[5.84333333 3.054      3.75866667 1.19866667]




# Class 4

## Exercise 6.1/6.2 -> Implementing stratified splitting test using iris dataset

In [29]:
from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split,stratified_train_test_split

iris_dataset = read_csv('/home/sa_bruno/Documentos/GitHub/si/datasets/iris/iris.csv', features=True, label=True)

train, test = train_test_split(iris_dataset, test_size=0.2, random_state=42)    
train_strat, test_strat = stratified_train_test_split(iris_dataset, test_size=0.2, random_state=42)


print("Train test split")
print(f"Iris dataset: {iris_dataset.shape()}")
print()
print(f"Training dataset: {train.shape()}")
print()
print(f"Testing dataset: {test.shape()}")
print()
print()

print("Stratified train test split")
print(f"Iris dataset: {iris_dataset.shape()}")
print()
print(f"Training dataset: {train_strat.shape()}")
print()
print(f"Testing dataset: {test_strat.shape()}")

Train test split
Iris dataset: (150, 4)

Training dataset: (120, 4)

Testing dataset: (30, 4)


Stratified train test split
Iris dataset: (150, 4)

Training dataset: (120, 4)

Testing dataset: (30, 4)


## Exercise 7.1 -> Implementing the RMSE test

In [30]:
from si.metrics.rmse import rmse
import numpy as np 

# compare with sklearn

from sklearn.metrics import mean_squared_error as mean_squared_error_skl
from sklearn.metrics import mean_absolute_error as mean_absolute_error_skl
from sklearn.metrics import r2_score as r2_score_skl

y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1, 2, 3, 6, 20])


our_rmse = rmse(y_true, y_pred)
skl_rmse = mean_squared_error_skl(y_true, y_pred, squared=False)

assert np.allclose(our_rmse, skl_rmse)

print(f"our rmse = {our_rmse}")
print(f"sklearn rmse = {skl_rmse}")


our rmse = 6.767569726275452
sklearn rmse = 6.767569726275452


## Exercise 7.2/7.3 -> Implementing the KNNRegressor test using cpu.csv

In [31]:
from si.data.dataset import Dataset
from si.model_selection.split import train_test_split
from si.models.knn_regressor import KNNRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from si.io.csv_file import read_csv

dataset_ = read_csv('/home/sa_bruno/Documentos/GitHub/si/datasets/cpu/cpu.csv', features=True, label=True)
dataset_train, dataset_test = train_test_split(dataset_, test_size=0.2)

knn = KNNRegressor(k=3)

knn.fit(dataset_train)

score = knn.score(dataset_test)
print(f'The rmse of the model is: {score}')

# compare with sklearn

knn_skl = KNeighborsRegressor(n_neighbors=3)

knn_skl.fit(dataset_train.X, dataset_train.y)

score_skl = mean_squared_error(dataset_test.y, knn_skl.predict(dataset_test.X), squared=False)
print(f'The rmse_skl of the model is: {score_skl}')

The rmse of the model is: 81.3592188582519
The rmse_skl of the model is: 81.36153382890387


## Optional Exercise -> Implementing the CategoricalNB Test



In [60]:
from si.models.categorical_nb import CategoricalNB
from si.model_selection.split import train_test_split

dataset = Dataset.from_random(1000, 5, 3)
train, test = train_test_split(dataset, 0.3)
nb = CategoricalNB()
nb.fit(train)
nb.predict(test)
print(f"Our Accuracy = {nb.score(test)}")


# test using sklearn 

from sklearn.naive_bayes import CategoricalNB as CategoricalNB_sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.X, dataset.y, test_size=0.3, stratify=dataset.y)
nb_sklearn = CategoricalNB_sklearn()
nb_sklearn.fit(X_train, y_train)

print(f"Sklearn Accuracy = {nb_sklearn.score(X_test, y_test)}")



Our Accuracy = 0.38666666666666666
Sklearn Accuracy = 0.38


# Class 5

## Exercise 8 -> Implementing RidgeRegression with Least Squares

In [33]:
from si.data.dataset import Dataset
from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares
from si.metrics.mse import mse

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
dataset_ = Dataset(X=X, y=y)


print('Our model')
model = RidgeRegressionLeastSquares()
model.fit(dataset_)

print(f"Parameters: {model.theta}")
print(f"Intercept: {model.theta_zero}")

score = model.score(dataset_)
print(f"Score: {score}")

y_pred_ = model.predict(Dataset(X=np.array([[3, 5]])))
print(f"Predictions: {y_pred_}")

print()

print('Compare with sklearn')

from sklearn.linear_model import Ridge
model = Ridge()    
X = (dataset_.X - np.nanmean(dataset_.X, axis=0)) / np.nanstd(dataset_.X, axis=0)
model.fit(X, dataset_.y)
print(f"Parameters: {model.coef_}") # should be the same as theta
print(f"Intercept: {model.intercept_}") # should be the same as theta_zero
print(f"Score: {mse(dataset_.y, model.predict(X))}")
print(f"Predictions: {model.predict(np.array([[3, 5]]))}") # should be the same as y_pred_

Our model
Parameters: [0.58823529 1.08145743]
Intercept: 8.5
Score: 0.07698961937716277
Predictions: [14.85294118]

Compare with sklearn
Parameters: [0.58823529 1.08145743]
Intercept: 8.5
Score: 0.07698961937716259
Predictions: [15.67199303]


# Class 7

## Exercise 9,1/9.2 -> Implementing the RandomForestClassifier class test using iris.csv

In [34]:
from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split
from si.models.random_forest_classifier import RandomForestClassifier

data = read_csv('/home/sa_bruno/Documentos/GitHub/si/datasets/iris/iris.csv', sep=',', features=True, label=True)
train, test = train_test_split(data, test_size=0.33, random_state=42)
model = RandomForestClassifier(n_estimators=5, min_samples_split=3, max_depth=3, mode='gini')
model.fit(train)
print('Our model')
print(f'Score {model.score(test)}')
print()


from sklearn.ensemble import RandomForestClassifier as RFC
print('Compare with sklearn')
model = RFC(n_estimators=3, min_samples_split=3, max_depth=3, criterion='gini')
model.fit(train.X, train.y)
print(f'Score {model.score(test.X, test.y)}')


Our model
Score 1.0

Compare with sklearn
Score 0.9795918367346939


## Exercise 10 -> Implementing the StackingClassifier ensemble test using breast-bin.csv

In [35]:
from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split
from si.models.knn_classifier import KNNClassifier
from si.models.logistic_regression import LogisticRegression
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.ensemble.stacking_classifier import StackingClassifier

data = read_csv('/home/sa_bruno/Documentos/GitHub/si/datasets/breast_bin/breast-bin.csv', sep=',', features=True, label=True)

train, test = train_test_split(data, test_size=0.33, random_state=42)

knn = KNNClassifier(5)

lr = LogisticRegression(0.01, 1000)

dt = DecisionTreeClassifier(2, 10)

knn2 = KNNClassifier(5)

#create a StackingClassifier model using the previous classifiers. The second KNNClassifier model must be used as the final model.
sc = StackingClassifier([knn, lr, dt], knn2)

#Train the StackingClassifier model. What is the score of the model on the test set?
sc.fit(train)
print(f'Our model score: {sc.score(test)}')

# sklearn 
from sklearn.ensemble import StackingClassifier as StackingClassifierSK
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
#create a StackingClassifier model using the previous classifiers. The second KNNClassifier model must be used as the final model.
sc = StackingClassifierSK(estimators=[('knn', KNeighborsClassifier(5)), ('lr', LogisticRegression()), ('dt', DecisionTreeClassifier())], final_estimator=KNeighborsClassifier(5))
#Train the StackingClassifier model. What is the score of the model on the test set?
sc.fit(train.X, train.y)
print(f'Sklearn model score: {sc.score(test.X, test.y)}')

/home/sa_bruno/anaconda3/envs/mestrado_si/lib/python3.11/site-packages/si-0.0.1-py3.11.egg/si/models/logistic_regression.py:176: RuntimeWarning: divide by zero encountered in log
  cost = (dataset.y * np.log(predictions)) + (1 - dataset.y) * np.log(1 - predictions)
/home/sa_bruno/anaconda3/envs/mestrado_si/lib/python3.11/site-packages/si-0.0.1-py3.11.egg/si/models/logistic_regression.py:176: RuntimeWarning: invalid value encountered in multiply
  cost = (dataset.y * np.log(predictions)) + (1 - dataset.y) * np.log(1 - predictions)
/home/sa_bruno/anaconda3/envs/mestrado_si/lib/python3.11/site-packages/si-0.0.1-py3.11.egg/si/statistics/sigmoid_function.py:18: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-X))


Our model score: 0.9652173913043478
Sklearn model score: 0.9695652173913043


# Class 8
## Exercise 11 -> Implementing the randomized_search_cv function test using breast-bin.csv

In [36]:
from si.io.csv_file import read_csv
from si.models.logistic_regression import LogisticRegression
from si.model_selection.cross_validation import k_fold_cross_validation
from si.model_selection.grid_search import grid_search_cv
from si.model_selection.randomized_search import randomized_search_cv

breast_dataset = read_csv('/home/sa_bruno/Documentos/GitHub/si/datasets/breast_bin/breast-bin.csv', sep=',', features=True, label=True)

lg = LogisticRegression()

hyperparameter_grid = {
    'l2_penalty': np.linspace(1, 10, 10),
    'alpha': np.linspace(0.001, 0.0001, 100),
    'max_iter': np.linspace(1000, 2000, 200)
}

scores = randomized_search_cv(lg,
                        breast_dataset,
                        hyperparameter_grid=hyperparameter_grid,
                        cv=3,
                        n_iter=10
                        )

print(f'Best hyperparameters: {scores["best_hyperparameters"]}')
print(f'Best score: {scores["best_score"]}')

Best hyperparameters: [6.0, 0.001, 1859.2964824120604]
Best score: 0.9683908045977011


# Class 9
## Exercise 12.1 -> Implementing the Dropout layer test

In [37]:
from si.neural_networks.layers import Dropout

dropout = Dropout(0.5)

np.random.seed(42)
X = np.random.randint(0, 10, size=(1, 10))

print(f'Input: {X}')
print()

print(f'Output: {dropout.forward_propagation(X, training=True)}')
print()

print(f'Backward pass: {dropout.backward_propagation(X)}')
print()


Input: [[6 3 7 4 6 9 2 6 7 4]]

Output: [[12.  6.  0.  8. 12.  0.  0.  0.  0.  8.]]

Backward pass: [[6 3 0 4 6 0 0 0 0 4]]



## Exercise 13.1 -> Implementing the TanhActivation class test

In [38]:
from si.neural_networks.activation import TanhActivation

tanh = TanhActivation()

np.random.seed(42)
X = np.random.randint(-5, 5, size=(1, 10))

print(f'Input: {X}')
print()

print(f'Output: {tanh.forward_propagation(X, training=True)}')
print()

print(f'Backward pass: {tanh.backward_propagation(X)}')


Input: [[ 1 -2  2 -1  1  4 -3  1  2 -1]]

Output: [[ 0.76159416 -0.96402758  0.96402758 -0.76159416  0.76159416  0.9993293
  -0.99505475  0.76159416  0.96402758 -0.76159416]]

Backward pass: [[ 0.41997434 -0.14130165  0.14130165 -0.41997434  0.41997434  0.0053638
  -0.02959811  0.41997434  0.14130165 -0.41997434]]


## Exercise 13.2 -> Implementing the SoftmaxActivation class

In [39]:
from si.neural_networks.activation import SoftmaxActivation

softmax = SoftmaxActivation()

np.random.seed(42)
X = np.random.randint(0, 5, size=(1, 10))


print(f'Input: {X}')
print()

print(f'Output: {softmax.forward_propagation(X, training=True)}')
print()

print(f'Backward pass: {softmax.backward_propagation(X)}')

Input: [[3 4 2 4 4 1 2 2 2 4]]

Output: [[0.07418408 0.20165325 0.0272908  0.20165325 0.20165325 0.01003972
  0.0272908  0.0272908  0.0272908  0.20165325]]

Backward pass: [[0.20604242 0.64395686 0.05309202 0.64395686 0.64395686 0.00993893
  0.05309202 0.05309202 0.05309202 0.64395686]]


## Exercise 14 -> Implementing the CategoricalCrossEntropy Class

In [40]:
from si.neural_networks.losses import CategoricalCrossEntropy


cce = CategoricalCrossEntropy()

np.random.seed(42)
X = np.random.randint(0, 5, size=(1, 5))

np.random.seed(42)
y = np.random.random(5)

print(f'Input: {X}')
print()
print(f'Target: {y}')
print()

print(f'Output: {cce.loss(X, y)}')
print()
print(f'Gradient: {cce.derivative(X, y)}')

Input: [[3 4 2 4 4]]

Target: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Output: 13.255676952536477

Gradient: [[ -8.00982284  -4.20736279  -2.73226305  -6.6816058  -25.63796216]]


## Exercise 15 -> Implementing the Adam class

In [41]:
from si.neural_networks.optimizers import Adam

adam = Adam()

np.random.seed(42)
X = np.random.randint(0, 5, size=(1, 5))

np.random.seed(42)
y = np.random.random(5)

print(f'Input: {X}')
print()
print(f'Target: {y}')
print()

print(f'Output: {adam.update(X, y)}')

Input: [[3 4 2 4 4]]

Target: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Output: [[2.99 3.99 1.99 3.99 3.99]]


## Exercise 16 -> Build, train and evaluate a neural network

In [42]:
from si.neural_networks.losses import BinaryCrossEntropy
from si.neural_networks.optimizers import SGD
from si.neural_networks.neural_network import NeuralNetwork
from si.data.dataset import Dataset
from si.model_selection.split import train_test_split
from si.data.dataset import Dataset
from si.neural_networks.layers import DenseLayer
from si.neural_networks.activation import ReLUActivation, SigmoidActivation
from si.neural_networks.losses import BinaryCrossEntropy
from si.metrics.accuracy import accuracy
from si.model_selection.split import train_test_split

dataset = Dataset(X=np.random.rand(500, 32), y=np.random.randint(0, 2, 500))
train, test = train_test_split(dataset)

net = NeuralNetwork(epochs=100, batch_size=16, optimizer=SGD, learning_rate=0.01, verbose=False,
                    loss=BinaryCrossEntropy, metric=accuracy)
n_features = dataset.X.shape[1]

net.add(DenseLayer(16, (n_features,)))
net.add(ReLUActivation())
net.add(DenseLayer(8))
net.add(ReLUActivation())
net.add(DenseLayer(1))
net.add(SigmoidActivation())


net.fit(train)

# compare with keras

from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.metrics import Accuracy
from tensorflow.keras.layers import Dense


dataset = Dataset(X=np.random.rand(500, 32), y=np.random.randint(0, 2, 500))
train, test = train_test_split(dataset)

model = Sequential()
model.add(Dense(16, activation='relu', input_shape=(32,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer=SGD(learning_rate=0.01), loss=BinaryCrossentropy(), metrics=[Accuracy()])
model.fit(train.X, train.y, epochs=100, batch_size=16, verbose=False)

print(f'Our Test score: {net.score(test)}')
print(f'Keras Test score: {model.evaluate(test.X, test.y)}')

2023-12-18 01:29:44.846866: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-18 01:29:44.912865: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-18 01:29:45.251576: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-18 01:29:45.251702: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-18 01:29:45.307289: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

Our Test score: 0.54
4/4 [==============================] - 0s 6ms/step - loss: 0.6855 - accuracy: 0.0000e+00
Keras Test score: [0.6855418682098389, 0.0]


# Class 11
## Exercise 17 -> Implementing the One-Hot-Encoding

In [43]:
from si.encoding.one_hot_encoder import OneHotEncoder

data = ['b', 'r', 'u', 'n', 'o', 's', 'a']

# create a one hot encoder
encoder = OneHotEncoder(padder=None, max_length=None)

# fit the encoder
encoder.fit(data)

# transform the data
print(f'Input: {data}')

# transform the data
print(f'Output: {encoder.transform(data)}')

# inverse transform the data
print(f'Inverse transform: {encoder.inverse_transform(encoder.transform(data))}')

print()
print("With padder")

encoder_p = OneHotEncoder(padder='a', max_length=2)

# fit the encoder
encoder_p.fit(data)

# transform the data
print(f'Input: {data}')

# transform the data
print(f'Output: {encoder_p.transform(data)}')

# inverse transform the data
print(f'Inverse transform: {encoder_p.inverse_transform(encoder_p.transform(data))}')

Input: ['b', 'r', 'u', 'n', 'o', 's', 'a']
Output: [[[0, 0, 1, 0, 0, 0, 0]], [[0, 0, 0, 0, 1, 0, 0]], [[1, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 1, 0, 0, 0]], [[0, 1, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 1]], [[0, 0, 0, 0, 0, 1, 0]]]
Inverse transform: [['b'], ['r'], ['u'], ['n'], ['o'], ['s'], ['a']]

With padder
Input: ['b', 'r', 'u', 'n', 'o', 's', 'a']
Output: [[[0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0]], [[0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 1, 0]], [[1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0]], [[0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0]], [[0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0]], [[0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 1, 0]], [[0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1, 0]]]
Inverse transform: [['b', 'a'], ['r', 'a'], ['u', 'a'], ['n', 'a'], ['o', 'a'], ['s', 'a'], ['a', 'a']]


## Exercise 18 -> Implementing the CNN

PATH: /si/scripts/cnn_exercise.ipynb